// sample/src/components/HapticButton/index.tsx
import { useState } from "react";
import "./style.css";
import { useHaptic } from "use-haptic";

export const HapticButton = () => {
  const [isContinuous, setIsContinuous] = useState(false);
  const [duration, setDuration] = useState(5000);
  const [interval, setInterval] = useState(100);
  const { triggerHaptic } = useHaptic();

  const handleClick = () => {
    if (isContinuous) {
      const startTime = Date.now();

      const continuousVibration = () => {
        if (Date.now() - startTime < duration) {
          triggerHaptic();
          setTimeout(continuousVibration, interval);
        }
      };

      continuousVibration();
    } else {
      triggerHaptic();
    }
  };

  return (
    <div className="haptic-btn-container">
      <button className="haptic-btn" onClick={handleClick} type="button">
        Feel Haptic !!!
      </button>
      <label>
        <input
          type="checkbox"
          checked={isContinuous}
          onChange={() => setIsContinuous((prev) => !prev)}
        />
        Continuous Haptic
      </label>
      <label>
        Duration (ms):
        <input
          type="number"
          value={duration}
          onChange={(e) => setDuration(Number(e.target.value))}
        />
      </label>
      <label>
        Interval (ms):
        <input
          type="number"
          value={interval}
          onChange={(e) => setInterval(Number(e.target.value))}
        />
      </label>
    </div>
  );
};

// sample/vite-vue/src/components/HapticButton/index.vue
<script setup lang="ts">
import { ref } from "vue";
import { useHaptic } from "vue-haptic";
import "./style.css";

const isContinuous = ref(false);
const duration = ref(5000);
const interval = ref(100);
const { triggerHaptic } = useHaptic();

const handleClick = () => {
  if (isContinuous.value) {
    const startTime = Date.now();

    const continuousVibration = () => {
      if (Date.now() - startTime < duration.value) {
        triggerHaptic();
        setTimeout(continuousVibration, interval.value);
      }
    };

    continuousVibration();
  } else {
    triggerHaptic();
  }
};
</script>

<template>
  <div class="haptic-btn-container">
    <button class="haptic-btn" @click="handleClick" type="button">
      Feel Haptic !!!
    </button>
    <label>
      <input
        type="checkbox"
        v-model="isContinuous"
      />
      Continuous Haptic
    </label>
    <label>
      Duration (ms):
      <input
        type="number"
        v-model.number="duration"
      />
    </label>
    <label>
      Interval (ms):
      <input
        type="number"
        v-model.number="interval"
      />
    </label>
  </div>
</template>
